[variables]
PHP_VERSION = "8.3"

[phases.setup]
nixPkgs = ["mysql-client"]

[start]
cmd = "php artisan migrate --force && php artisan db:seed --force && php artisan storage:link --force && php artisan serve --host=0.0.0.0 --port=$PORT"
